# Generated by Django 5.1 on 2024-09-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_airplane_airplane_type_alter_airport_city_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "seat", "row")},
        ),
    ]
