# Generated by Django 5.1 on 2024-09-14 17:54

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airport_image_file_path
            ),
        ),
    ]
