# Generated by Django 5.1 on 2024-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0007_airport_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(blank=True, to="airport.crew"),
        ),
    ]
